baseurl = "https://www.iofarmit.com/"
languageCode = "en-us"
title = "IoFarmIT"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "ioFarmIT"
	description = "Our system relies on machine learning algorithms to process data gathered from the sensors using a <b>state-of-the-art wireless technology</b>. It provides an easy user interface where farmers can also share and learn best practices. farm data machine learning iot sensor predict fungi"

	# The path must be relative to the static folder
	favicon = "faviconz.ico"


	# Navigation
	[params.navigation]
		brand = "ioFarmIT"

		[params.navigation.links]
			about     = "About"
			services  = "Solutions"
			portfolio = "Team"
			contact   = "Contact"
			


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "The Internet of Farms"
		subtitle   = ""
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "Smart Farming Solutions"
    description = "<b>Agriculture efficiency and sustainability</b> are some of the key challenges of this century in a world of ever-expanding population.<br>The UN projects that the worldwide demand for food will increase by more than 50% by 2050. Currently 80% of the food worldwide is produced by individual or family farms. This provides a unique opportunity for integration of information technology in <b>Smart Farming</b>. <br><br>That's why <b>our mission</b> is to build an <b>Internet of Farms</b> to support farmers around the world.<br><br>Our system relies on machine learning algorithms to process data gathered from the sensors using a <b>state-of-the-art wireless technology</b>. It provides an <b>easy user interface</b> where farmers can also share and learn best practices."
    buttonText  = "Go to Demo"


	# Service section
	[params.services]
		headline = "What we do"

        [[params.services.list]]
			icon = "fa-connectdevelop"
			title = "Sensors Selection"
			description = "We help you to choose the right set of tools to collect the data that you want"


        [[params.services.list]]
            icon = "fa-empire" 
            title = "Data Management"
            description = "We collect, store and organised your data in an efficent way"


		[[params.services.list]]
            icon = "fa-area-chart"
            title = "Machine Learning"
            description = "Get a deeper understand of your filed with the most advanced techniques"

        [[params.services.list]]
            icon = "fa-tv"
            title = "Web Application"
            description = "Query, visualise and use all your data in a simple interface to make better decisions"


    # Portfolio modals
#	[params.portfolio.modal]
#        client = "Client"
 #       date = "Date"
#        buttonText = "Close"

    # Aside section
	#[params.aside]
	#	headline = "Check the demo of our web application"

	#	[params.aside.button]
	#		text = "Go to Demo"
	#		link = "http://www.app.iofarmit.com/app/myfarm/"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Send us an email and we will get back to you as soon as possible!"
		#phone = "123-456-6789"
		email = "info@iofarmit.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
	
	
	
	##### IL COLORE GIUSTO è VERDE #16B42B #########
