baseurl = ""
languageCode = "en-us"
title = "iofarmit"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "ioFarmIT"
	description = "farm data machine learning iot sensor predict fungi"

	# The path must be relative to the static folder
	favicon = "faviconz.ico"


	# Navigation
	[params.navigation]
		brand = "ioFarmIT"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Team"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Real-time Smart Farming Solutions"
		subtitle   = ""
		buttonText = "Find out more"


	# About section
	[params.about]
		headline    = "Smart Farming Solutions"
		description = "At IoFarmit we are developing a decision support system relying both on an easy user interface backed by machine learning algorithms and on a cost-effective & efficient hardware. Our solution is targeted to farms of any size."
		buttonText  = "Go to Demo"


	# Service section
	[params.services]
		headline = "What we do"

        [[params.services.list]]
            icon = "fa-empire" 
            title = "Data collection & integration"
            description = "Our templates are updated regularly so they don't break."

        [[params.services.list]]
			icon = "fa-connectdevelop"
			title = "Sensors"
			description = "You can use this theme as is, or you can make changes!"

		[[params.services.list]]
            icon = "fa-area-chart"
            title = "Machine Learning"
            description = "We update dependencies to keep things fresh."

        [[params.services.list]]
            icon = "fa-tv"
            title = "Web application"
            description = "You have to make your websites with love these days!"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Check the demo of our web application"

		[params.aside.button]
			text = "Go to Demo"
			link = "http://iofarmit.com/app/myfarm/"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		#phone = "123-456-6789"
		email = "info@iofarmit.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
	
	
	
	##### IL COLORE GIUSTO è VERDE #16B42B #########
